---
- name: deploy nginx config
  become: true
  template:
    force: yes
    src: ./etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart_nginx

- name: Configure service
  become: true
  systemd:
    name: nginx
    enabled: yes

