---
- hosts: inetRouter
  become: true
  tasks:
    - name: Enable ipv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: addressing and routing
      command: "{{item}}"
      with_items:
        - iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
        - ip route add 192.168.1.0/24 via 192.168.255.9 dev eth1
        - ip route add 192.168.2.0/24 via 192.168.255.9 dev eth1
        - ip route add 192.168.0.0/24 via 192.168.255.9 dev eth1
        - ip route add 192.168.255.0/30 via 192.168.255.9 dev eth1
        - ip route add 192.168.255.4/30 via 192.168.255.9 dev eth1
    - name: Restart network
      systemd:
        state: restarted
        name: network

- hosts: centralRouter
  become: true
  tasks:
    - name: Enable ipv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: routing
      command: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ip route del default
        - ip route add default via 192.168.255.10 dev eth1
        - ip addr add 192.168.0.17/28 dev eth4 
        - ip addr add 192.168.0.33/28 dev eth4
        - ip addr add 192.168.0.65/26 dev eth4
        - ip route add 192.168.2.0/24 via 192.168.255.1 dev eth3
        - ip route add 192.168.1.0/24 via 192.168.255.5 dev eth2
- hosts: office2Router
  become: true
  tasks:
    - name: Enable ipv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: routing
      command: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ip r del default
        - ip r add default via 192.168.255.6 dev eth1
        - ip addr add 192.168.1.129/26 dev eth2
        - ip addr add 192.168.1.193/26 dev eth2


- hosts: office1Router
  become: true
  tasks:
    - name: Enable ipv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: routing&&addressing
      command: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ip addr add 192.168.2.65/26 dev eth2
        - ip addr add 192.168.2.129/26 dev eth2
        - ip addr add 192.168.2.193/26 dev eth2
        - ip route del default
        - ip route add default via 192.168.255.2 dev eth1
- hosts: centralServer
  become: true
  tasks:
    - name: Central-Server
      command: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ip route del default
        - ip route add default via 192.168.0.17 dev eth1
- hosts: office1Server
  become: true
  tasks:
    - name: Office2-Server
      command: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ip route del default
        - ip route add default via 192.168.2.65 dev eth1

- hosts: office2Server
  become: true
  tasks:
    - name: Office2-Server
      command: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ip route del default
        - ip route add default via 192.168.1.129  dev eth1