---
- name: Copy LOGSTASH cfg files
  become: true
  copy: 
    force: yes
    src: "./templates/etc/logstash/"
    dest: "/etc/logstash/conf.d/"
  notify: elk_restart

- name: Copy Elasticsearch cfg
  become: true
  copy:
    force: yes
    src: "./templates/etc/elasticsearch/elasticsearch.yml"
    dest: "/etc/elasticsearch/elasticsearch.yml"
  notify: elk_restart

- name: Copy Kibana cfg
  become: true
  copy:
    force: yes
    src: "./templates/etc/kibana/kibana.yml"
    dest: "/etc/kibana/kibana.yml"
  notify: elk_restart

- name: Enable ELK stack
  become: true
  systemd:
   name: "{{ item }}"
   enabled: yes
  with_items:
      - 'logstash'
      - 'elasticsearch'
      - 'kibana'
  notify:
    - elk_restart

