---
- name: add repo
  become: true
  copy:
    force: yes
    src: "./templates/etc/yum.repos.d/"
    dest: "/etc/yum.repos.d/" 

- name: Install  gpg keys
  become: true
  rpm_key:
    state: present
    key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

- name: Install ELK
  become: true
  yum:
    name: [java,elasticsearch,kibana,logstash]
    state: present
  notify: elk_restart
  
- name: Reload daemon
  become: true
  systemd:
    daemon_reload: yes
  notify:
    - elk_restart


