---
- name: Configure Journal remote
  become: true
  template:
    force: yes
    src: etc/systemd/systemd-journal-remote.service.j2
    dest: /lib/systemd/system/systemd-journal-remote.service
  notify:
    - restart_jremote
    
- name: daemon_reload
  become: true
  command: 'systemctl daemon-reload'
  notify:
    - restart_jremote



- name: Enable systemd-journal-remote
  become: true
  systemd:
    name: systemd-journal-remote
    enabled: yes
  notify:
    - restart_jremote