---
- name: Add epel-release repo
  become: true
  yum:
    name: epel-release
    state: present

- name: Install IPA server
  become: true
  ignore_errors: yes
  yum:
    name: ['ipa-server', 'ipa-server-dns', 'bind-dyndb-ldap']
    state: present
