---
- name: Clean NGINX html folder
  become: true
  find:
    paths: "/usr/share/nginx/html/"
    recurse: true
    file_type: any
  register: files_to_delete

- name: Ansible remove file glob
  become: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  notify:
    - restart_nginx
