---
#gathering_facts: true
- name: Install&&Config Nginx on RedHat|Cent
  include: install_nginx_rhel.yml
  when: (ansible_facts['distribution'] == "RedHat") or 
        (ansible_facts['distribution'] == "CentOS")

- name: Change default cfg
  include: configure_nginx.yml

- name: Clean html
  include: clean_html.yml

- name: Create repo in nginx_html
  include: create_repo.yml