---
- name: Add epel-release repo
  become: true
  yum:
    name: epel-release
    state: present

- name: Install NGINX
  become: true
  yum:
    name: ['nginx']
    state: present
  notify:
    - restart_nginx


