---
- name: Add creds
  include_vars:
    file: "{{ creds_file_path }}"
- name: Configure hostname IPA Server
  become: true
  hostname:
    name: "{{ ipa_server }}.{{ domain_name }}"

- name: Configure /etc/hosts
  become: true
  template:
    force: yes
    src: ./etc/hosts.j2
    dest: /etc/hosts

- name: Configure IPA Server
  become: true
  command: "{{ item }}"
  ignore_errors: yes
  with_items:
    - "ipa-server-install --hostname={{ ipa_server }}.{{ domain_name }} --domain={{ domain_name }} --realm={{ realm }} --ds-password={{ ipa_supercreds }} --admin-password={{ ipa_supercreds }}  --mkhomedir --setup-dns --forwarder=8.8.8.8 --auto-reverse --unattended"