---
- name: Enable|Disable ipv4 forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Disable|Enable rp_filtering
  become: true
  sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv4.conf.all.rp_filter 
    - net.ipv4.conf.eth1.rp_filter
    - net.ipv4.conf.eth2.rp_filter
    - net.ipv4.conf.eth3.rp_filter
    - net.ipv4.conf.eth4.rp_filter

- name: Restart network
  become: true
  systemd:
    state: restarted
    name: network
      
- name: enable Quagaa
  become: true
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - ospfd
    - zebra
  notify: reload_quagaa

- name: Configure Quagaa&Zebra
  become: true
  template: 
    force: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: './etc/quagga/zebra_router.conf.j2', dest: '/etc/quagga/zebra.conf' }
    - { src: './etc/quagga/ospf_router.conf.j2', dest: '/etc/quagga/ospfd.conf' }
  notify: reload_quagaa

- name: Selinux&chowning
  become: true
  command: "{{ item }}"
  ignore_errors: yes
  with_items:
    - "setsebool -P zebra_write_config 1"
    - "chown -R quagga:quaggavt /etc/quagga/"
  notify: reload_quagaa
