---
- name: Configure Journal Upload
  become: true
  template:
    force: yes
    src: etc/systemd/journal-upload.conf.j2
    dest: /etc/systemd/journal-upload.conf
  notify:
    - restart_jupload
    
- name: Configure Journal Upload
  become: true
  template:
    force: yes
    src: etc/systemd/systemd-journal-upload.service.j2
    dest: /usr/lib/systemd/system/systemd-journal-upload.service
  notify:
    - restart_jupload

- name: Enable systemd-journal-upload
  become: true
  systemd:
    name: systemd-journal-upload
    enabled: yes
  notify:
    - restart_jupload
    
- name: Daemon-Reload
  become: true
  command: 'systemctl daemon-reload'
  notify:
    - restart_jupload