---
- name: MAKE BACKUP
  become: true
  #become_method: su
  become_user: postgres
  ignore_errors: true
  command: "{{ item }}"
  with_items:
    - rm -rf /var/lib/pgsql/11/data
    - mkdir -p /var/lib/pgsql/11/data
    - chown -R postgres:postgres /var/lib/pgsql/11/data
    - "/usr/pgsql-11/bin/pg_basebackup -h 192.168.10.10 -U replica -D /var/lib/pgsql/11/data -X s"
    - chmod 0700 -R "/var/lib/pgsql/11/data"

- name: Copy REPLICA PGSQL CFG
  become: true
  template: 
    owner: postgres
    force: true
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0700'
  with_items:
    - { src: "recovery.conf.j2", dest: "/var/lib/pgsql/11/data/recovery.conf" }
    - { src: "pg_hba.conf.j2", dest: "/var/lib/pgsql/11/data/pg_hba.conf" }
    - { src: "postgres.conf.j2", dest: "/var/lib/pgsql/11/data/postgresql.conf" }
  notify: reload_pgsql

- name: ENABLE REPLICA PGSQL
  become: true
  systemd:
    name: postgresql-11
    state: stopped
    enabled: true
  notify: reload_pgsql
    